node:
  cluster: test-cluster
  id: test-id

admin:
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9191

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 9097
    filter_chains:
    - filters:
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: tcp_proxy
          cluster: test-cluster

  clusters:
  - name: discoveryservice
    connect_timeout: 10s
    type: EDS
    eds_cluster_config:
      service_name: discoveryservice
      eds_config:
        path: "/envoy-config/eds.yaml"
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: discoveryservice
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: envoy-cluster-sd.iias-metrics.svc.cluster.local
                port_value: 3036


dynamic_resources:
  cds_config:
    api_config_source:
      transport_api_version: V3
      refresh_delay: 5s
      api_type: REST
      cluster_names: [discoveryservice]


