node:
  cluster: test-cluster
  id: test-id

admin:
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9191

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 9097
    filter_chains:
    - filters:
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: tcp_proxy
          cluster: test-cluster

  clusters:
  # Application cluster - endpoints discovered via EDS
  - name: test-cluster
    type: EDS
    connect_timeout: 0.25s
    lb_policy: ROUND_ROBIN
    eds_cluster_config:
      service_name: test-cluster
      eds_config:
        resource_api_version: V3
        api_config_source:
          api_type: REST
          transport_api_version: V3
          cluster_names: [discoveryservice]
          refresh_delay: 5s
          set_node_on_first_message_only: true

  # Flask EDS server - static address
  - name: discoveryservice
    type: STATIC
    connect_timeout: 10s
    lb_policy: ROUND_ROBIN
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http_protocol_options: {}
    load_assignment:
      cluster_name: discoveryservice
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 5123
